[package]
type = 'bash'
name = 'neodkms'
slug = 'ndkms'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
binDirs = []
sourceDirs = []
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
